# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cnstr.xdc

# Block Designs: bd/design_04/design_04.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04 || ORIG_REF_NAME==design_04} -quiet] -quiet

# IP: bd/design_04/ip/design_04_processing_system7_0_0/design_04_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04_processing_system7_0_0 || ORIG_REF_NAME==design_04_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_04/ip/design_04_ps7_0_axi_periph_0/design_04_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_04_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_04/ip/design_04_rst_ps7_0_100M_0/design_04_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_04_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_04/ip/design_04_ay_ledsw_0_4/design_04_ay_ledsw_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04_ay_ledsw_0_4 || ORIG_REF_NAME==design_04_ay_ledsw_0_4} -quiet] -quiet

# IP: bd/design_04/ip/design_04_auto_pc_0/design_04_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_04_auto_pc_0 || ORIG_REF_NAME==design_04_auto_pc_0} -quiet] -quiet

# XDC: bd/design_04/design_04_ooc.xdc
