# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_07/project_07.srcs/constrs_1/new/btn_led_cstrn.xdc

# Block Designs: bd/design_02/design_02.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_02 || ORIG_REF_NAME==design_02} -quiet] -quiet

# IP: bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_02_processing_system7_0_0 || ORIG_REF_NAME==design_02_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_t07_debounce_top_0_0/design_02_t07_debounce_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_02_t07_debounce_top_0_0 || ORIG_REF_NAME==design_02_t07_debounce_top_0_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_util_vector_logic_0_0/design_02_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_02_util_vector_logic_0_0 || ORIG_REF_NAME==design_02_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/design_02/design_02_ooc.xdc
