# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_02/design_02.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02 || ORIG_REF_NAME==design_02} -quiet] -quiet

# IP: bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02_processing_system7_0_0 || ORIG_REF_NAME==design_02_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_axi_gpio_0_0/design_02_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02_axi_gpio_0_0 || ORIG_REF_NAME==design_02_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_auto_pc_0/design_02_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02_auto_pc_0 || ORIG_REF_NAME==design_02_auto_pc_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_ps7_0_axi_periph_0/design_02_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_02_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_02/ip/design_02_rst_ps7_0_100M_0/design_02_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_02_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_02_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_02/project_02.gen/sources_1/bd/design_02/design_02_ooc.xdc
