# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_08/project_08.srcs/sources_1/bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xci
# IP: The module: 'design_02_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_08/project_08.srcs/sources_1/bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_02_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_08/project_08.srcs/sources_1/bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xci
# IP: The module: 'design_02_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arify/WorkSpace/ZEDboard_vhdlNc/project_08/project_08.srcs/sources_1/bd/design_02/ip/design_02_processing_system7_0_0/design_02_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_02_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
